stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    params:
      - train.batch_size
      - train.lr
    outs:
      - full_model.pth
      - training_data.json
      - test_data.pt
  evaluate:
    cmd: python evaluate.py
    deps:
      - evaluate.py
      - test_data.pt
      - full_model.pth
    params:
      - train.batch_size
    outs:
      - loss.png
      - confusion_matrix.csv
    plots:
     - metrics.json:
         template: simple
         x: Recall
         y: Specificity
         cache: false
  export:
    cmd: python export_model.py
    deps:
      - export_model.py
      - full_model.pth
    params:
      - train.batch_size
    outs:
      - mnist_model_1.onnx
      - mnist_model_2.onnx
      - mnist_model_4.onnx
      - mnist_model_8.onnx
      - mnist_model_16.onnx
      - mnist_model_32.onnx
      - mnist_model_64.onnx
      - mnist_model_128.onnx
      - mnist_model_256.onnx
  measure:
    cmd: python measure.py
    deps:
      - test_data.pt
      - measure.py
      - mnist_model_1.onnx
      - mnist_model_2.onnx
      - mnist_model_4.onnx
      - mnist_model_8.onnx
      - mnist_model_16.onnx
      - mnist_model_32.onnx
      - mnist_model_64.onnx
      - mnist_model_128.onnx
      - mnist_model_256.onnx
      - bar_1.json
      - bar_2.json
      - bar_3.json
    params:
      - train.batch_size
    outs:
      - tensorrt_inteference.txt
    plots:
     -  throughput_results.json:
         template: bar_2.json
         x: batch_size
         y: throughput_batches_per_s
         cache: false
     - throughput_results_2.json:
         template: bar_1.json
         x: batch_size
         y: throughput_images_per_s
         cache: false
     - latency_results.json:
         template: bar_3.json
         x: batch_size
         y: value
         cache: false
