stages:
  train:
    cmd: python train.py
    deps:
      - train.py
    params:
      - train.batch_size
      - train.lr
    outs:
      - full_model.pth
      - training_data.json
      - test_data.pt
  evaluate:
    cmd: python evaluate.py
    deps:
      - evaluate.py
      - test_data.pt
      - full_model.pth
    params:
      - train.batch_size
    outs:
      - loss.png
      - confusion_matrix.csv
    plots:
     - metrics.json:
         template: simple
         x: Recall
         y: Specificity
         cache: false
  export:
    cmd: python export_model.py
    deps:
      - export_model.py
      - full_model.pth
    params:
      - train.batch_size
    outs:
      - mnist_model.onnx
  measure:
    cmd: python measure.py
    deps:
      - test_data.pt
      - measure.py
      - mnist_model.onnx
    params:
      - train.batch_size
    outs:
      - tensorrt_inteference.txt



#tensor.rt latenz, nvidia (lädt onyx) accuracy nochmal messen, und durchsatz